### ISSUE TITLE
2.2.1 in npm does not have host option

### ISSUE THREAD

**Issue by MattMcFarland** [tomekwi/elm-live#33] opened 2016-05-26 18:42 UTC
Hi, can you please publish a new version to npm?  The latest right now does not have the `--host` changes.  Was really confused..

**Comment by tomekwi** [comment] 2016-05-26 18:53
I’ll do it tomorrow if you’re okay to wait.

**Comment by MattMcFarland** [comment] 2016-05-26 19:20
Yeah, thanks! In the meantime I'm just npm installing the github repo, but `--port` is not working either, it is actually trying to pass `--port` to `elm make` instead...

**Comment by tomekwi** [comment] 2016-05-27 10:36
I’ve released this as v2.3.0 right now.

Yeah, unit tests are definitely [there](https://github.com/tomekwi/elm-live/blob/master/test.js). We’re doing our best to have 100% coverage. I’ve never noticed the problem with `--port` you’ve mentioned. If you manage to reproduce this with a unit test, it’d be wonderful! Perhaps it’s a question of `--port=PORT` vs `--port PORT` (we don’t support the latter yet).

I’m closing this, since the original problem is resolved. If you have any more problems, feel free to give a shout. Thanks!

**Closed by tomekwi** 2016-05-27 10:36 UTC
