### ISSUE TITLE
Watching symlinked files results in infinite loop

### ISSUE THREAD

**Issue by nicklawls** [tomekwi/elm-live#74] opened 2016-10-18 16:11 UTC
First things first, elm-live is awesome! I see at as an integral part of the elm experience. 

Here's my issue

My directory structure looks something like this: 

```
src/Foobar.elm
static/Foobar
├── Foobar.css
├── Foobar.html
├── Foobar.js
├── app.js
└── bundle.js
deploy/
├── app.py
├── foo -> ../static/
├── json
│   └── weather.json
└── reload.sh

```

Notice the `foo -> ../static/`, which denotes that `foo` is a symlinked copy of `static` from the parent directory. 

when I run `elm-live src/Foobar.elm --output=static/Foobar/app.js --dir=./static` It gets caught in an infinite loop, repeating the following message

```
Success! Compiled 1 module.
Successfully generated  static/Foobar/app.js

elm-live: 
    You've changed `deploy/foo/Foobar/app.js`. Rebuilding!
```

I'm not a big js hacker, but depending on how big of a fix you think it'd be, I can implement it and submit a pr. Thanks so much!!!!

**Comment by tomekwi** [comment] 2016-10-24 07:55
Hey man, thanks a lot for reporting this. I’m pretty surprised this happens, because elm-live is designed to [only watch `*.elm` files](https://github.com/tomekwi/elm-live/blob/b8670829b49a4e5c63cf33a3d86e85fb5d6fedfa/source/elm-live.js#L187). If you can hack together a quick solution to your problem, I’ll be happy to help you turn it into a well-tested PR.

Also, it’d be good if you keep an eye on #72 – we’ll probably be working on the watch glob soon. If you find anything suspicious, it’d be good to batch it with our work there.

**Comment by tomekwi** [comment] 2017-01-09 10:20
Just managed to reproduce the issue! 🎉

@nicklawls could you please check if this patch helps? https://github.com/tomekwi/elm-live/commit/55acbb07c343678a5719d34d17928caf7b9c0880

**Comment by tomekwi** [comment] 2017-01-11 14:15
Just checked this patch out on a real project, works like wonders. Will be merging this in a sec.

**Comment by tomekwi** [comment] 2017-01-11 14:18
🎉 

Fix released in v2.7.4.

**Closed by tomekwi** 2017-01-11 14:18 UTC
Labels: waiting for feedback

**Comment by nicklawls** [comment] 2017-01-11 18:39
Thanks for fixing this Tomek! Sorry I wasn't able to help

**Comment by tomekwi** [comment] 2017-01-11 18:45
Did it solve your issue? If not, give me a shout and I’ll reopen 🙂

**Comment by nicklawls** [comment] 2017-01-11 18:56
I changed my directory structure (for a couple different reasons) so that
there were no symlinks, so I can't test it against my original use case.
But if I encounter it again I will definitely let you know!
